from .auth_views import *
from .dashboard_views import *
from .teacher_views import *
from .student_views import *
from .attendance_views import *
from .report_views import *
from .analytics_views import *
from .face_views import *
from .settings_views import *
from .helper_views import *
