from .auth_views import *
from .dashboard_views import *
from .attendance_views import *

from ..views import analytics_view
from ..views import reports_page
from ..views import export_csv_report
from ..views import download_pdf_report
from ..views import performance_report
from ..views import register_face
from ..views import face_attendance_page
from ..views import start_face_attendance
from ..views import attendance_history
from ..views import add_student
from ..views import students_list
from ..views import update_student
from ..views import delete_student
from ..views import student_detail
from ..views import add_teacher
from ..views import update_teacher
from ..views import delete_teacher
from ..views import admin_teachers
from ..views import analytics
from ..views import settings_page